-- MySQL Script generated by MySQL Workbench
-- Tue Jun  4 16:05:43 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema notas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema notas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `notas` DEFAULT CHARACTER SET utf8 ;
USE `notas` ;

-- -----------------------------------------------------
-- Table `notas`.`docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notas`.`docente` (
  `id_docente` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(64) NOT NULL,
  `apellidos` VARCHAR(64) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `sexo` SET('FEMENINO', 'MASCULINO', 'INDEFINIDO') NOT NULL,
  `dui` VARCHAR(10) NOT NULL,
  `nit` VARCHAR(17) NOT NULL,
  `especialidad` VARCHAR(64) NOT NULL,
  `tipo_usuario` SET('DOCENTE', 'ADMINISTRADOR') NOT NULL,
  `pass` VARCHAR(255) NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_docente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notas`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notas`.`curso` (
  `id_curso` INT NOT NULL AUTO_INCREMENT,
  `nombre_curso` VARCHAR(128) NOT NULL,
  `cohorte` VARCHAR(64) NOT NULL,
  `descripcion` VARCHAR(128) NOT NULL,
  `duracion` VARCHAR(64) NOT NULL,
  `sede` VARCHAR(64) NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  `nivel` INT NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  PRIMARY KEY (`id_curso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notas`.`tipo_modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notas`.`tipo_modulo` (
  `id_tipo_modulo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_tipo_modulo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notas`.`modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notas`.`modulo` (
  `id_modulo` INT NOT NULL AUTO_INCREMENT,
  `nombre_modulo` VARCHAR(64) NOT NULL,
  `descripcion_modulo` VARCHAR(255) NOT NULL,
  `horas_modulo` VARCHAR(64) NOT NULL,
  `tipo_modulo` INT NOT NULL,
  `evaluacion1` TINYINT NOT NULL,
  `evaluacion2` TINYINT NULL,
  `evaluacion3` TINYINT NULL,
  `evaluacion4` TINYINT NULL,
  `evaluacion5` TINYINT NULL,
  `evaluacion6` TINYINT NULL,
  `estado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_modulo`),
  INDEX `fk_tipo_modulo_idx` (`tipo_modulo` ASC),
  CONSTRAINT `fk_tipo_modulo`
    FOREIGN KEY (`tipo_modulo`)
    REFERENCES `notas`.`tipo_modulo` (`id_tipo_modulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notas`.`participante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notas`.`participante` (
  `id_participante` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(64) NOT NULL,
  `apellidos` VARCHAR(64) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `sexo` SET('FEMENINO', 'MASCULINO', 'INDEFINIDO') NOT NULL,
  `dui` VARCHAR(10) NULL DEFAULT NULL,
  `nit` VARCHAR(17) NULL DEFAULT NULL,
  `carnet_minoridad` VARCHAR(15) NULL DEFAULT NULL,
  `direccion` VARCHAR(64) NOT NULL,
  `telefono` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `pass` VARCHAR(255) NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_participante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notas`.`modulos_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notas`.`modulos_curso` (
  `id_modulos_curso` INT NOT NULL AUTO_INCREMENT,
  `id_curso` INT NOT NULL,
  `id_modulo` INT NOT NULL,
  `id_docente` INT NOT NULL,
  `observaciones` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_modulos_curso`),
  INDEX `fk_id_curso_idx` (`id_curso` ASC),
  INDEX `fk_docente_modulo_idx` (`id_docente` ASC),
  CONSTRAINT `fk_id_curso`
    FOREIGN KEY (`id_curso`)
    REFERENCES `notas`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_modulo`
    FOREIGN KEY (`id_modulo`)
    REFERENCES `notas`.`modulo` (`id_modulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_docente_modulo`
    FOREIGN KEY (`id_docente`)
    REFERENCES `notas`.`docente` (`id_docente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notas`.`nota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notas`.`nota` (
  `id_nota` INT NOT NULL AUTO_INCREMENT,
  `id_participante` INT NOT NULL,
  `id_modulos_curso` INT NOT NULL,
  `nota1` FLOAT(2,2) NOT NULL DEFAULT 0.0,
  `nota2` FLOAT(2,2) NULL,
  `nota3` FLOAT(2,2) NULL,
  `nota4` FLOAT(2,2) NULL,
  `nota5` FLOAT(2,2) NULL,
  `nota6` FLOAT(2,2) NULL,
  `observaciones` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_nota`),
  INDEX `fk_mxp_idx` (`id_modulos_curso` ASC),
  INDEX `fk_participante_idx` (`id_participante` ASC),
  CONSTRAINT `fk_mxp`
    FOREIGN KEY (`id_modulos_curso`)
    REFERENCES `notas`.`modulos_curso` (`id_modulos_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_participante`
    FOREIGN KEY (`id_participante`)
    REFERENCES `notas`.`participante` (`id_participante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notas`.`matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notas`.`matricula` (
  `id_matricula` INT NOT NULL AUTO_INCREMENT,
  `id_curso` INT NOT NULL,
  `id_participante` INT NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  `observaciones` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_matricula`),
  INDEX `fk_id_curso2_idx` (`id_curso` ASC),
  INDEX `fk_id_estudiante2_idx` (`id_participante` ASC),
  CONSTRAINT `fk_id_curso2`
    FOREIGN KEY (`id_curso`)
    REFERENCES `notas`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_estudiante2`
    FOREIGN KEY (`id_participante`)
    REFERENCES `notas`.`participante` (`id_participante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notas`.`porcentajes_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notas`.`porcentajes_curso` (
  `id_porcentajes_curso` INT NOT NULL AUTO_INCREMENT,
  `id_curso` INT NOT NULL,
  `id_tipo_modulo` INT NOT NULL,
  `porcentaje` DOUBLE NOT NULL,
  `observacion` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id_porcentajes_curso`),
  INDEX `fk_tipo_porcentaje_idx` (`id_tipo_modulo` ASC),
  INDEX `fk_curso_porcentajes_idx` (`id_curso` ASC),
  CONSTRAINT `fk_tipo_porcentaje`
    FOREIGN KEY (`id_tipo_modulo`)
    REFERENCES `notas`.`tipo_modulo` (`id_tipo_modulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_curso_porcentajes`
    FOREIGN KEY (`id_curso`)
    REFERENCES `notas`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
